name: 'cloud_cost_optimization'
version: '1.0.0'
config-version: 2

profile: 'cloud_cost_optimization'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cloud_cost_optimization:
    staging:
      +materialized: view
    marts:
      +materialized: table
